### ISSUE TITLE
Module '"react-intl"' has no exported member 'useIntl'

### ISSUE THREAD

**Issue by marques-p44** [formatjs/react-intl#1321]
I'm trying to use the `useIntl` hook in react-intl@3.0.0_beta.8, but I'm unable to import it. I am getting a TS error.

### Expected behavior
I expect to be able to import `useIntl` from react-intl.

### Current behavior
TS error `Module '"react-intl"' has no exported member 'useIntl'`

### Step to reproduce for BUG REPORT
`yarn add react-intl@3.0.0-beta-8`
In your code:
```js
import { useIntl } from 'react-intl';
```

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.0.0-beta-8 |
|      `npm ls react` | 16.8.6 |
|     `npm --version` | 6.4.1 |
|    `node --version` | 10.15.3 |
| yarn --version | 1.15.2 | 
| tsc --version | 3.5.1 | 

| OS   | Version |
| ---- | ------- |
| macOS Mojave | 10.14.5 |

| Browser | Version |
| ------- | ------- |
| Brave    | 0.65.118 Chromium: 75.0.3770.80 |

**Comment by longlho** [comment]
Thanks for reporting! The DefinitelyTyped type definition is probably not accounting for beta. We're porting react-intl to TS per #1306 so it should be fixed in the next beta version.

**Comment by marques-p44** [comment]
ok cool, thanks for the quick response :)

**Comment by raul1991** [comment]
I am still facing this issue with react-intl: ^5.24.0 @longlho

**Comment by longlho** [comment]
Try removing your lock file and reinstall

**Comment by MO-Elmu** [comment]
I am also facing this issue with 5.24.1 did removing the lock file made a difference it didn't in my case.

**Comment by iliogr** [comment]
I am currently having the same issue with 6.6.6
