### ISSUE TITLE
Regression: missing "key" prop warning

### ISSUE THREAD

**Issue by mvestergaard** [formatjs/react-intl#1359]
#1354 re-introduced an issue where using rich content values in `<FormattedMessage>` causes warnings about missing keys.

This change specifically https://github.com/formatjs/react-intl/pull/1354/files#diff-02d37c347364c13c106d74a9319ab545R157

There's a comment already mentioning that `React.createElement` should be used to avoid this warning.

**Comment by longlho** [comment]
Thanks for reporting. We'll take a look asap.

**Comment by longlho** [comment]
fixed in #1361

**Comment by HollyPony** [comment]
According to the sample in the documentation I'm still experiencing in 3.1.12 by this sample code : https://codesandbox.io/s/formatjsreact-intlissues1359-fftes . 

I'm not sure this is fully related to this issue so I can open a new one on demand
