### ISSUE TITLE
Typescript compiler (tsc) fails to compile index.ts files

### ISSUE THREAD

**Issue by alexiwonder** [formatjs/react-intl#1468]
### Expected behavior
I've made a very simple project with only one `tsx` file which has only two statements:
```
import React from 'react';
import { IntlProvider } from "react-intl";
```
Main dependencies are just `react`, `typescript`, and `react-intl`. Nothing fancy; plain and simple.
It is expected that `tsc -noEmit` returns without any error/output, but it doesn't here. Tested with a `.ts` file and the same result.

### Current behavior
fails with several errors regarding compiling files- mainly `*.index.ts`. Example:
`node_modules/react-intl/dist/utils.d.ts(22,225): error TS1109: Expression expected.`

### Step to reproduce for BUG REPORT
- Clone https://github.com/alexiwonder/react-intl-ts-test 
- Run `npm install` and then `tsc -noEmit` in command line

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.1.13|
|      `npm ls react` | 16.9|
|     `npm --version` | 6.6.0|
|    `node --version` | 10.16.3|

| OS   | Version |
| ---- | ------- |
| Windows| 17134|

**Comment by longlho** [comment]
I've updated the docs for TS usage: https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#typescript-usage

Thanks a lot for reporting!

**Comment by alexiwonder** [comment]
Thanks @longlho, but I still get the same error, plus the following:
`error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'esnext', 'dom', 'dom.iterable', 'webworker', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.promise', 'es2018.regexp', 'esnext.array', 'esnext.asynciterable'.`

What am I missing here?

**Comment by longlho** [comment]
I tried on the repo you posted and it works. Maybe your TS version is too low, thus missing some libs

**Comment by alexiwonder** [comment]
Oh, sorry! My mistake. Cheers.
